Performing system checks...

Traceback (most recent call last):
  File "webui/manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/home/morris/.local/share/virtualenvs/asoco-crawler-z9_vET4T/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/morris/.local/share/virtualenvs/asoco-crawler-z9_vET4T/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/morris/.local/share/virtualenvs/asoco-crawler-z9_vET4T/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/morris/.local/share/virtualenvs/asoco-crawler-z9_vET4T/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 60, in execute
    super().execute(*args, **options)
  File "/home/morris/.local/share/virtualenvs/asoco-crawler-z9_vET4T/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/morris/.local/share/virtualenvs/asoco-crawler-z9_vET4T/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 95, in handle
    self.run(**options)
  File "/home/morris/.local/share/virtualenvs/asoco-crawler-z9_vET4T/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 104, in run
    self.inner_run(None, **options)
  File "/home/morris/.local/share/virtualenvs/asoco-crawler-z9_vET4T/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/home/morris/.local/share/virtualenvs/asoco-crawler-z9_vET4T/lib/python3.7/site-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/morris/.local/share/virtualenvs/asoco-crawler-z9_vET4T/lib/python3.7/site-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/morris/.local/share/virtualenvs/asoco-crawler-z9_vET4T/lib/python3.7/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/morris/.local/share/virtualenvs/asoco-crawler-z9_vET4T/lib/python3.7/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/morris/.local/share/virtualenvs/asoco-crawler-z9_vET4T/lib/python3.7/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/morris/.local/share/virtualenvs/asoco-crawler-z9_vET4T/lib/python3.7/site-packages/django/urls/resolvers.py", line 398, in check
    for pattern in self.url_patterns:
  File "/home/morris/.local/share/virtualenvs/asoco-crawler-z9_vET4T/lib/python3.7/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/morris/.local/share/virtualenvs/asoco-crawler-z9_vET4T/lib/python3.7/site-packages/django/urls/resolvers.py", line 579, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/morris/.local/share/virtualenvs/asoco-crawler-z9_vET4T/lib/python3.7/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/morris/.local/share/virtualenvs/asoco-crawler-z9_vET4T/lib/python3.7/site-packages/django/urls/resolvers.py", line 572, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/morris/.local/share/virtualenvs/asoco-crawler-z9_vET4T/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/morris/git/pyprojects/asoco-crawler/webui/json_manager/urls.py", line 20, in <module>
    import main.views
  File "/home/morris/git/pyprojects/asoco-crawler/webui/main/views.py", line 14, in <module>
    schema = json.load(open(settings.SCHEMA_JSON, encoding='utf8'))
  File "/home/morris/apps/python-3.7.0/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/morris/apps/python-3.7.0/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/morris/apps/python-3.7.0/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/morris/apps/python-3.7.0/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 287 (char 286)
Killed
